### ISSUE TITLE
Pair button doesn't work when iOS view setting is set to zoomed

### ISSUE THREAD

**Issue by devinbileck** [joachimneumann/bisqremote_iOS#10]
There was a user in the Keybase #support channel reporting that the "Pair" button doesn’t work on iOS - it is totally unresponsive.

App version 1.4
iPhone 6s, running iOS 14.7.1

I wonder if it is a result of a small screen size and the text overlapping the clickable button area.

![A7023A2D-73A1-441C-ACFA-4C170FB9A774](https://user-images.githubusercontent.com/603793/128304200-01c60d99-50a8-45ad-909f-b9aaecc0dccb.jpg)

**Comment by devinbileck** [comment]
Note that I am unable to reproduce using the simulator with iPhone 6s running iOS 14.4.

**Comment by Olugbo** [comment]
It's a very odd issue that I only noticed recently. I dont know when exactly it started. Is it possible to get a link to download with older iOS versions of the app and test?

**Comment by Olugbo** [comment]
Issue reproduced and resolved; Go to Settings > Display & Brightness > View
If setting is "Zoomed", the "pair" button is inactive. If setting is "Standard" the button works as normal. Once paired, user can return back to zoomed view

**Comment by maxowenwilliams** [comment]
This issue does not seem to be resolved for all models; for example, it's still a problem for me on an iPhone SE, iOS 14.7.1, App version 1.4 (also of the smaller-screen variety).

There is no "View" setting, as Olugbo described, but there is something similar at Settings > Display & Brightness > Text Size

The text in the Bisq app does not appear to be dynamic, with the font size staying the same when this "Text Size" option is adjusted. Perhaps it is only the pair screen though: I cannot get through to check any other screen.

This produces the same screen as the image above: it trails off with "notifications suc...", which leaves the pair button unresponsive.

Reinstalling the app or rebooting while the text size is at its smallest does not help.

This has been the case for months now for me, probably since the start of the year or even earlier. I receive notifications, but cannot click through to find out what they are because it's stuck on the pair screen.

**Comment by devinbileck** [comment]
Thanks for the info @maxowenwilliams. I am now able to reproduce the issue using an iPhone SE on the simulator.
I will look into releasing a fix soon, hopefully next week sometime.

**Comment by onlymarcus** [comment]
> Issue reproduced and resolved; Go to Settings > Display & Brightness > View If setting is "Zoomed", the "pair" button is inactive. If setting is "Standard" the button works as normal. Once paired, user can return back to zoomed view

This happened with my iphone 12 mini, I followed these instructions and it solved
![WhatsApp Image 2022-05-06 at 14 51 40](https://user-images.githubusercontent.com/36059034/167188785-88d0b995-0523-4d44-b6c9-13cf97f474c9.jpeg)
.

**Comment by onlymarcus** [comment]
> Issue reproduced and resolved; Go to Settings > Display & Brightness > View If setting is "Zoomed", the "pair" button is inactive. If setting is "Standard" the button works as normal. Once paired, user can return back to zoomed view

**This happened with my iphone 12 mini, I followed these instructions and it solved**
![WhatsApp Image 2022-05-06 at 14 51 40](https://user-images.githubusercontent.com/36059034/167189616-8dc7378b-8815-49ce-9174-e872478c704f.jpeg)
